[workspace]
members = [
   "client",
   "proxy",
   "prover",    
]
resolver = "2"



[patch.crates-io]
rustls = { git = "https://github.com/zypher-network/rustls", default-features = false, features = ["logging", "std", "tls12", "ring"] }