[package]
name = "prover"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-std = "0.5"
ark-ff = "0.5"
ark-bn254 = "0.5"
ark-groth16  = {version = "0.5", default-features =false}
ark-r1cs-std = "0.5"
ark-snark  = "0.5"
ark-relations = "0.5"
